spring:
  application:
    name: slotify-backend

  # hilos virtuales de Java 25
  threads:
    virtual:
      enabled: true

  # POSTGRE
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/appdb?currentSchema=reserves
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  # REDIS
  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}

  # ELASTIC
  elasticsearch:
    uris: http://${ELASTIC_HOST:elastic-es-http}:9200
    username: elastic
    password: ${ELASTIC_PASSWORD}

  # KEYCLOAK
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:keycloak}:80/realms/${KEYCLOAK_REALM:slotify}/protocol/openid-connect/certs

  # OLLAMA
  ai:
    ollama:
      base-url: http://${OLLAMA_HOST:ollama}:11434
      chat:
        model: llama3:instruct

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  javadoc-enabled: true # Soporte nativo para Markdown en Javadoc (Java 25)

# LOGS
logging:
  level:
    org.springframework.security: INFO
    com.slotify.backend: DEBUG

# PROPIEDAD REUTILIZABLE
keycloak:
  server-url: http://${KEYCLOAK_HOST:keycloak}:80
  realm: ${KEYCLOAK_REALM:slotify}
