-- MySQL Script generated by MySQL Workbench
-- Sun Apr  5 19:55:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reserves
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reserves
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reserves` DEFAULT CHARACTER SET utf8 ;
USE `reserves` ;

-- -----------------------------------------------------
-- Table `reserves`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`users` (
  `user_id` CHAR(36) NOT NULL,
  `username` VARCHAR(70) NOT NULL,
  `s3_image_key` VARCHAR(200) NULL,
  `phone_number` VARCHAR(15) NULL,
  `email_address` VARCHAR(320) NULL UNIQUE,
  `created_at` TIMESTAMP NOT NULL,
  `created_by_company_id` CHAR(36) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`companies` (
  `user_id` CHAR(36) NOT NULL,
  `default_max_concurrent_services` INT NOT NULL,
  `company_name` VARCHAR(200) NOT NULL,
  `phone_number` VARCHAR(15) NULL,
  `email_address` VARCHAR(320) NOT NULL UNIQUE,
  `physical_address` VARCHAR(300) NOT NULL,
  `s3_image_key` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `ratting_avg` TINYINT(7) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`services` (
  `service_id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `service_name` VARCHAR(45) NOT NULL,
  `service_minutes_duration` INT NOT NULL,
  `s3_image_key` VARCHAR(200) NULL,
  `service_price_cent` INT NOT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `company_id_idx` (`company_id` ASC),
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `reserves`.`companies` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`reserves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`reserves` (
  `reserve_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `service_id` CHAR(36) NOT NULL,
  `service_time` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `is_canceled` TINYINT NOT NULL,
  PRIMARY KEY (`reserve_id`),
  INDEX `fk_users_has_services_services1_idx` (`service_id` ASC),
  INDEX `fk_users_has_services_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_has_services_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reserves`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_services_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `reserves`.`services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`conversations` (
  `conversation_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `modified_at` TIMESTAMP NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `summary` TEXT NULL,
  PRIMARY KEY (`conversation_id`),
  INDEX `fk_conversations_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_conversations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reserves`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`message` (
  `message_id` CHAR(36) NOT NULL,
  `conversation_id` CHAR(36) NOT NULL,
  `text_content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `sender_rol` ENUM('USER', 'SYSTEM') NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_message_conversations1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_message_conversations1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `reserves`.`conversations` (`conversation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`notifications` (
  `notification_id` CHAR(36) NOT NULL,
  `companies_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `notification_sender` ENUM("USER", "COMPANY") NOT NULL,
  `text_content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`notification_id`),
  INDEX `fk_notifications_companies1_idx` (`companies_id` ASC),
  INDEX `fk_notifications_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notifications_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `reserves`.`companies` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reserves`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`max_concurrent_services_interval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`max_concurrent_services_interval` (
  `interval_id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `start_datetime` TIMESTAMP NOT NULL,
  `end_datetime` TIMESTAMP NOT NULL,
  `max_concurrent_services` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`interval_id`),
  INDEX `fk_max_concurrent_services_interval_companies1_idx` (`company_id` ASC),
  CONSTRAINT `fk_max_concurrent_services_interval_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `reserves`.`companies` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`service_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`service_schedule` (
  `service_schedule_id` CHAR(36) NOT NULL,
  `service_id` CHAR(36) NOT NULL,
  `day_of_week` INT NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  PRIMARY KEY (`service_schedule_id`),
  CONSTRAINT `fk_service_schedule_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `reserves`.`services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserves`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserves`.`reviews` (
  `review_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `stars` INT NOT NULL,
  `text_content` TEXT NULL,
  `reserve_id` CHAR(36) NOT NULL,
  INDEX `fk_users_has_companies_companies1_idx` (`company_id` ASC),
  INDEX `fk_users_has_companies_users1_idx` (`user_id` ASC),
  PRIMARY KEY (`review_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `company_id_UNIQUE` (`company_id` ASC),
  INDEX `fk_reviews_reserves1_idx` (`reserve_id` ASC),
  CONSTRAINT `fk_users_has_companies_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `reserves`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_companies_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `reserves`.`companies` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_reserves1`
    FOREIGN KEY (`reserve_id`)
    REFERENCES `reserves`.`reserves` (`reserve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
